None-ya Business
bbriggs/legos.devopsy pull request #5
Opened 2017-02-09 15:05 UTC by drewpearce

I’m gonna run out of None jokes soon.
Lego checks for None also has error exception handling now.

2017-02-09 18:23 UTC, sacres requested changes
Also will need to rebase due to previous merge.

2017-02-09 18:23 UTC, sacres commented on legos/devopsy.py
> +        if message['test'] is not None:
Thanks for the PR @drewpearce! Seems you have a typo here: 's/'test'/'text'/

2017-02-16 18:09 UTC, drewpearce commented on legos/devopsy.py
> +        if message['test'] is not None:
fixed typo

2017-02-16 18:39 UTC, sacres commented
Thanks @drewpearce but you still need to rebase against master.

2017-02-16 19:43 UTC, bbriggs commented
Looks good. We'll change the interpolation in another PR.

2017-02-16 19:43 UTC, bbriggs approved these changes

2017-02-16 19:53 UTC, sacres commented
What? It reverts my changes... which are already merged in master..

2017-02-16 19:57 UTC, bbriggs commented
That's not what I'm seeing in the diff.
http://imgur.com/a/pRzt5

What are you seeing?

2017-02-16 21:05 UTC, drewpearce commented
closing to avoid this mess. will resubmit later off of an updated branch.

2017-02-16 21:05 UTC, closed without merging